#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Weathi.Resource", IsApplication=true)]

namespace Weathi
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050002
			public const int accent = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int primary = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int primaryDark = 2131034113;
			
			// aapt resource value: 0x7f050004
			public const int splash_background = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int textblockColor = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int textblockColorCondition = 2131034118;
			
			// aapt resource value: 0x7f050003
			public const int window_background = 2131034115;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int background = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int background2 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int chill = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int compass = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int downarrow = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int errorCloud = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int humidity = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int iconWeathi = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int options = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int pin = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int pressure = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int refresh = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int rounded_edge = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int splash_logo = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int splash_screen = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int uparrow = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int visibility = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int wind = 2130837521;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080001
			public const int Image = 2131230721;
			
			// aapt resource value: 0x7f080010
			public const int ImgHumidity = 2131230736;
			
			// aapt resource value: 0x7f080012
			public const int ImgPressure = 2131230738;
			
			// aapt resource value: 0x7f080014
			public const int ImgVisibility = 2131230740;
			
			// aapt resource value: 0x7f08001a
			public const int List = 2131230746;
			
			// aapt resource value: 0x7f080009
			public const int btnOptions = 2131230729;
			
			// aapt resource value: 0x7f080008
			public const int btnRefresh = 2131230728;
			
			// aapt resource value: 0x7f080004
			public const int errorStackPanel = 2131230724;
			
			// aapt resource value: 0x7f08000b
			public const int linearLayout4 = 2131230731;
			
			// aapt resource value: 0x7f080007
			public const int mainStackPanel = 2131230727;
			
			// aapt resource value: 0x7f08001c
			public const int radioCelsius = 2131230748;
			
			// aapt resource value: 0x7f08001b
			public const int radioFarenheit = 2131230747;
			
			// aapt resource value: 0x7f080006
			public const int reloadButton = 2131230726;
			
			// aapt resource value: 0x7f080019
			public const int textAddress = 2131230745;
			
			// aapt resource value: 0x7f080016
			public const int textChill = 2131230742;
			
			// aapt resource value: 0x7f080017
			public const int textDirection = 2131230743;
			
			// aapt resource value: 0x7f080005
			public const int textError = 2131230725;
			
			// aapt resource value: 0x7f080011
			public const int textHumidity = 2131230737;
			
			// aapt resource value: 0x7f080013
			public const int textPressure = 2131230739;
			
			// aapt resource value: 0x7f080015
			public const int textVisibility = 2131230741;
			
			// aapt resource value: 0x7f080018
			public const int textWindSpeed = 2131230744;
			
			// aapt resource value: 0x7f08000a
			public const int txtCondition = 2131230730;
			
			// aapt resource value: 0x7f080000
			public const int txtDay = 2131230720;
			
			// aapt resource value: 0x7f080002
			public const int txtHigh = 2131230722;
			
			// aapt resource value: 0x7f08000c
			public const int txtHighTempCondition = 2131230732;
			
			// aapt resource value: 0x7f08000e
			public const int txtLocation = 2131230734;
			
			// aapt resource value: 0x7f080003
			public const int txtLow = 2131230723;
			
			// aapt resource value: 0x7f08000d
			public const int txtLowTempCondition = 2131230733;
			
			// aapt resource value: 0x7f08000f
			public const int txtText = 2131230735;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int FirstTime = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int ForecastItem = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int Main = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int Settings = 2130968579;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060006
			public const int ApplicationName = 2131099654;
			
			// aapt resource value: 0x7f060010
			public const int CancelButton = 2131099664;
			
			// aapt resource value: 0x7f060001
			public const int DirectionLabel = 2131099649;
			
			// aapt resource value: 0x7f060018
			public const int EastLabel = 2131099672;
			
			// aapt resource value: 0x7f06000e
			public const int GetLocationTitle = 2131099662;
			
			// aapt resource value: 0x7f060004
			public const int HumidityLabel = 2131099652;
			
			// aapt resource value: 0x7f06000a
			public const int NoConectionMessage = 2131099658;
			
			// aapt resource value: 0x7f06000b
			public const int NoGpsMessage = 2131099659;
			
			// aapt resource value: 0x7f060012
			public const int NorthEastLabel = 2131099666;
			
			// aapt resource value: 0x7f060011
			public const int NorthLabel = 2131099665;
			
			// aapt resource value: 0x7f060013
			public const int NorthWestLabel = 2131099667;
			
			// aapt resource value: 0x7f06000c
			public const int NotFoundMessage = 2131099660;
			
			// aapt resource value: 0x7f06000d
			public const int NotLocationMessage = 2131099661;
			
			// aapt resource value: 0x7f06000f
			public const int PleaseWaitMessage = 2131099663;
			
			// aapt resource value: 0x7f060002
			public const int PressureLabel = 2131099650;
			
			// aapt resource value: 0x7f060007
			public const int RefreshButton = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int SettingsTitle = 2131099656;
			
			// aapt resource value: 0x7f060015
			public const int SouthEastLabel = 2131099669;
			
			// aapt resource value: 0x7f060014
			public const int SouthLabel = 2131099668;
			
			// aapt resource value: 0x7f060016
			public const int SouthWestLabel = 2131099670;
			
			// aapt resource value: 0x7f060009
			public const int UnitsLabel = 2131099657;
			
			// aapt resource value: 0x7f060003
			public const int VisibilityLabel = 2131099651;
			
			// aapt resource value: 0x7f060017
			public const int WestLabel = 2131099671;
			
			// aapt resource value: 0x7f060005
			public const int WindChillLabel = 2131099653;
			
			// aapt resource value: 0x7f060000
			public const int WindLabel = 2131099648;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070001
			public const int MyTheme = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int MyTheme_Base = 2131165184;
			
			// aapt resource value: 0x7f070002
			public const int MyTheme_Splash = 2131165186;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
